# Generated by Django 5.0.6 on 2024-06-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_move_list_movie_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_list',
            old_name='Rating',
            new_name='rating',
        ),
    ]
