# Generated by Django 5.0.6 on 2024-06-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_rename_rating_movie_list_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_list',
            name='year',
            field=models.DateField(),
        ),
    ]
