# Generated by Django 5.0.6 on 2024-06-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_movie_list_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_list',
            name='year',
            field=models.IntegerField(),
        ),
    ]
